version: '3'
services:
  app:
    build: .
    image: lambda_libvips_demo
    environment:
      BUCKET_NAME: local-bucket
      AWS_REGION: 'ap-northeast-1'
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    volumes:
      - .:/var/task
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio:/storage
    command: ['server', '/storage', '--console-address', ':9001']
  mc:
    image: minio/mc:latest
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 minio_user minio_password;
      mc mb myminio/local-bucket;
      "
volumes:
  minio:
